<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PSNG564" name="com.advantage.tests.OptumOne.PlanOfCare" tests="1" failures="0" timestamp="18 Apr 2016 07:28:05 GMT" time="176.192" errors="1">
  <testcase name="runPlanOfCare" time="176.192" classname="com.advantage.tests.OptumOne.PlanOfCare">
    <error type="com.advantage.genericexceptions.ClickNoSuchElementException" message="Could not find &#039;New Patient Goal Button&#039; due to exception:  java.lang.NullPointerException:  null">
      <![CDATA[com.advantage.genericexceptions.ClickNoSuchElementException: Could not find 'New Patient Goal Button' due to exception:  java.lang.NullPointerException:  null
	at com.advantage.framework.Framework.click(Framework.java:1477)
	at com.advantage.framework.Framework.click(Framework.java:1405)
	at com.advantage.pages.OptumOne.PlanOfCarePage.clickNewPatientGoalButton(PlanOfCarePage.java:54)
	at com.advantage.tests.OptumOne.PlanOfCare.runPlanOfCare(PlanOfCare.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- runPlanOfCare -->
</testsuite> <!-- com.advantage.tests.OptumOne.PlanOfCare -->
